{
  "openapi": "3.0.0",
  "info": {
    "title": "Your API Title",
    "version": "1.0.0",
    "description": "Your API Description"
  },
  "paths": {
    "/terms_of_use": {
      "parameters": [
        {
          "name": "description",
          "in": "path",
          "description": "Descriptive text on details of rights and licensing.",
          "required": 0,
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "access_rights",
          "in": "path",
          "description": "Information about the conditions to access the resource or an indication of its security status.",
          "required": 1,
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "has_license",
          "in": "path",
          "description": "Reference to the legal document giving official permission to do something with the resource.",
          "required": 1,
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "kontaktní_bod",
          "in": "path",
          "description": "Contact point for the further details about the terms of use.",
          "required": 0,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "Terms of use defines overall conditions and rights regarding access and usage  of dataset. ",
        "description": "Terms of use defines overall conditions and rights regarding access and usage  of dataset. ",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {}
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "terms_of_use": {
        "type": "object",
        "properties": {
          "description": {
            "description": "Descriptive text on details of rights and licensing.",
            "type": "string"
          },
          "access_rights": {
            "description": "Information about the conditions to access the resource or an indication of its security status.",
            "type": "string"
          },
          "has_license": {
            "description": "Reference to the legal document giving official permission to do something with the resource.",
            "type": "string"
          },
          "kontaktní_bod": {
            "description": "Contact point for the further details about the terms of use.",
            "type": "string"
          }
        }
      }
    }
  }
}