{
  "openapi": "3.0.0",
  "info": {
    "title": "Your API Title",
    "version": "1.0.0",
    "description": "Your API Description"
  },
  "paths": {
    "/media_type": {
      "parameters": [],
      "get": {
        "summary": "A file format.",
        "description": "A file format.",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {}
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "media_type": {
        "type": "object",
        "properties": {}
      }
    }
  }
}