{
  "openapi": "3.0.0",
  "info": {
    "title": "Your API Title",
    "version": "1.0.0",
    "description": "Your API Description"
  },
  "paths": {
    "/organization": {
      "parameters": [
        {
          "name": "name",
          "in": "path",
          "description": "Name of the agent.",
          "required": 1,
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "has_identifier",
          "in": "path",
          "description": "has identifier",
          "required": 0,
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "má_kontaktní_bod",
          "in": "path",
          "description": "Relevant contact information for the catalogued resource. ",
          "required": 0,
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "alternate_name",
          "in": "path",
          "description": "To specify the organizational name associated with the object",
          "required": 0,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "Represents a collection of people organized together into a community or other social, commercial or political structure. The group has some common purpose or reason for existence which goes beyond the set of people belonging to it and can act as an Agent. Organizations are often decomposable into hierarchical structures. ",
        "description": "Represents a collection of people organized together into a community or other social, commercial or political structure. The group has some common purpose or reason for existence which goes beyond the set of people belonging to it and can act as an Agent. Organizations are often decomposable into hierarchical structures. ",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {}
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "organization": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the agent.",
            "type": "string"
          },
          "has_identifier": {
            "description": "has identifier",
            "type": "string"
          },
          "má_kontaktní_bod": {
            "description": "Relevant contact information for the catalogued resource. ",
            "type": "string"
          },
          "alternate_name": {
            "description": "To specify the organizational name associated with the object",
            "type": "string"
          }
        }
      }
    }
  }
}