{
  "openapi": "3.0.0",
  "info": {
    "title": "Your API Title",
    "version": "1.0.0",
    "description": "Your API Description"
  },
  "paths": {
    "/geometry": {
      "parameters": [
        {
          "name": "label",
          "in": "path",
          "description": "Label of geometry object.",
          "required": 0,
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "well_known_text_literal",
          "in": "path",
          "description": "Representation of geometry object as WKT Literal.",
          "required": 0,
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "geography_markup_language_literal",
          "in": "path",
          "description": "Representation of geometry object as GML Literal.",
          "required": 0,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "The Geometry class provides the means to identify a location as a point, line, polygon, etc. expressed using coordinates in some coordinate reference system.",
        "description": "The Geometry class provides the means to identify a location as a point, line, polygon, etc. expressed using coordinates in some coordinate reference system.",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {}
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "geometry": {
        "type": "object",
        "properties": {
          "label": {
            "description": "Label of geometry object.",
            "type": "string"
          },
          "well_known_text_literal": {
            "description": "Representation of geometry object as WKT Literal.",
            "type": "string"
          },
          "geography_markup_language_literal": {
            "description": "Representation of geometry object as GML Literal.",
            "type": "string"
          }
        }
      }
    }
  }
}