PREFIX ns0: <http://purl.org/dc/terms/>
PREFIX ns1: <http://www.w3.org/2000/01/rdf-schema#>
CONSTRUCT {
  ?v0 a ns0:MediaTypeOrExtent .
  ?v0 ns1:label ?v1 .
}
WHERE {
  ?v0 a ns0:MediaTypeOrExtent .
  OPTIONAL {
    ?v0 ns1:label ?v1 .
  }
}
