<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1" elementFormDefault="unqualified" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:sawsdl="http://www.w3.org/ns/sawsdl">
  <xs:complexType name="variable" sawsdl:modelReference="http://www.molmod.info/semantics/pims-ii.ttl#Variable">
    <xs:annotation>
      <xs:documentation xml:lang="de">
        Variable
      </xs:documentation>
      <xs:documentation xml:lang="en">
        Variable - Variable, i.e., a conventional that is employed for something to which values can be assigned (this may include different notations for the same variable including, e.g., computational representations); this is to be understood very generally, e.g., a variable may be an array or set of elements or have another kind of internal structure
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="iri" type="xs:anyURI"/>
      <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="variable" type="variable"/>
</xs:schema>
